sudo: required
#dist: precise
language: cpp

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - ^libc\+\+-dev$
      before_install:
        - sudo apt-get update -qq

      script:
        - mkdir build
        - cd build
        - export CXX=clang++-3.8
        - export CC=clang-3.8
        - cmake .. && make
        - bin/cf_test

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - ^libc\+\+-dev$
      before_install:
        - sudo apt-get update -qq

      script:
        - mkdir build
        - cd build
        - export CXX=clang++-3.7
        - export CC=clang-3.7
        - cmake .. && make
        - bin/cf_test
