sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - libc++-dev

      before_install:
        - sudo apt-get update -qq


      script:
        - mkdir build
        - cd build
        env:
          - CXX=clang++3.8
          - CC=clang-3.8
        - cmake .. 
        - make
        - bin/cf_test

